language: node_js
node_js:
  - '8.10'
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAI6NZ4VPRNCJJTRYQ
    - AWS_DEFAULT_REGION=eu-central-1
branches:
  only:
    - master
before_install:
script:
  - npm run lint
  - npm run test
  - npm run deploy-dev
notifications:
  email:
    on_failure: always

